[tool.pytest.ini_options]
addopts = "--cov=netemu --cov-report=html"

[tool.coverage.run]
concurrency = ["multiprocessing"]
parallel = true
sigterm = true
omit = [
    "/nix/*", # .direnv might point to nix store
    "tests/*",
    "netemu/__main__.py",
]
